version: '3'
services:
  app:
      image: ../app/.
      depends_on:
        - db
      deploy:
        replicas: 5
        restart_policy:
          condition: on-failure
      ports:
        - "5000:5000"
      networks:
        - appnet
        - dbnet
  db:
      image: mysql
      ports:
        - "3306:3306"
      volumes:
        - ./db:/var/lib/mysql
      environment:
        - MYSQL_DATABASE=rbac
        - MYSQL_ROOT_PASSWORD=badass
      networks:
        - dbnet
  nginx:
      image: nginx
      ports:
        - "5000:80"
      volumes:
        - ./nginx/conf.d:/etc/nginx/conf.d
      depends_on:
        - app
      networks:
        - appnet
networks:
    appnet:
    dbnet:
