-- MySQL Script generated by MySQL Workbench
-- Thu 28 Jun 2018 02:08:46 AM CST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema rbac
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema rbac
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `rbac` DEFAULT CHARACTER SET utf8 ;
USE `rbac` ;

-- -----------------------------------------------------
-- Table `rbac`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rbac`.`Users` (
  `id` INT NOT NULL,
  `username` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rbac`.`Roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rbac`.`Roles` (
  `id` INT NOT NULL,
  `rolename` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rbac`.`Permission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rbac`.`Permission` (
  `id` INT NOT NULL,
  `url` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rbac`.`Users_Roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rbac`.`Users_Roles` (
  `Users_id` INT NOT NULL,
  `Roles_id` INT NOT NULL,
  PRIMARY KEY (`Users_id`, `Roles_id`),
  INDEX `fk_Users_has_Roles_Roles1_idx` (`Roles_id` ASC),
  INDEX `fk_Users_has_Roles_Users1_idx` (`Users_id` ASC),
  CONSTRAINT `fk_Users_has_Roles_Users1`
    FOREIGN KEY (`Users_id`)
    REFERENCES `rbac`.`Users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Users_has_Roles_Roles1`
    FOREIGN KEY (`Roles_id`)
    REFERENCES `rbac`.`Roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rbac`.`Roles_Permission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rbac`.`Roles_Permission` (
  `Roles_id` INT NOT NULL,
  `Permission_id` INT NOT NULL,
  PRIMARY KEY (`Roles_id`, `Permission_id`),
  INDEX `fk_Roles_has_Permission_Permission1_idx` (`Permission_id` ASC),
  INDEX `fk_Roles_has_Permission_Roles1_idx` (`Roles_id` ASC),
  CONSTRAINT `fk_Roles_has_Permission_Roles1`
    FOREIGN KEY (`Roles_id`)
    REFERENCES `rbac`.`Roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Roles_has_Permission_Permission1`
    FOREIGN KEY (`Permission_id`)
    REFERENCES `rbac`.`Permission` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rbac`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rbac`.`user` (
  `id` INT NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NULL,
  `phone_number` VARCHAR(45) NULL,
  `image` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `rbac`.`restaurant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rbac`.`restaurant` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `infomation` VARCHAR(150) NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_restaurant_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_restaurant_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `rbac`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rbac`.`comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rbac`.`comment` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `star` INT NULL,
  `text` VARCHAR(150) NULL,
  `image` VARCHAR(45) NULL,
  `restaurant_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_comment_restaurant1_idx` (`restaurant_id` ASC),
  INDEX `fk_comment_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_comment_restaurant1`
    FOREIGN KEY (`restaurant_id`)
    REFERENCES `rbac`.`restaurant` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comment_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `rbac`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rbac`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rbac`.`order` (
  `id` INT NOT NULL,
  `date` DATE NULL,
  `desk_number` INT NULL,
  `total_price` FLOAT NULL,
  `restaurant_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_order_restaurant1_idx` (`restaurant_id` ASC),
  CONSTRAINT `fk_order_restaurant1`
    FOREIGN KEY (`restaurant_id`)
    REFERENCES `rbac`.`restaurant` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rbac`.`food`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rbac`.`food` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `price` FLOAT NULL,
  `food_type` VARCHAR(45) NULL,
  `description` VARCHAR(150) NULL,
  `image` VARCHAR(45) NULL,
  `available` TINYINT(1) NULL,
  `restaurant_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_food_restaurant1_idx` (`restaurant_id` ASC),
  CONSTRAINT `fk_food_restaurant1`
    FOREIGN KEY (`restaurant_id`)
    REFERENCES `rbac`.`restaurant` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rbac`.`order_history`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rbac`.`order_history` (
  `id` INT NOT NULL,
  `date` DATE NULL,
  `desk_number` INT NULL,
  `total_price` FLOAT NULL,
  `restaurant_id` INT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_order_history_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_order_history_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `rbac`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rbac`.`order_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rbac`.`order_item` (
  `id` INT NOT NULL,
  `number` INT NULL,
  `name` VARCHAR(45) NULL,
  `description` VARCHAR(150) NULL,
  `image` VARCHAR(45) NULL,
  `price` FLOAT NULL,
  `order_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_order_item_order1_idx` (`order_id` ASC),
  CONSTRAINT `fk_order_item_order1`
    FOREIGN KEY (`order_id`)
    REFERENCES `rbac`.`order` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rbac`.`order_history_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rbac`.`order_history_item` (
  `id` INT NOT NULL,
  `number` INT NULL,
  `name` VARCHAR(45) NULL,
  `description` VARCHAR(150) NULL,
  `image` VARCHAR(45) NULL,
  `price` FLOAT NULL,
  `order_history_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_order_history_item_order_history1_idx` (`order_history_id` ASC),
  CONSTRAINT `fk_order_history_item_order_history1`
    FOREIGN KEY (`order_history_id`)
    REFERENCES `rbac`.`order_history` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rbac`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rbac`.`role` (
  `id` INT NOT NULL,
  `rolename` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rbac`.`permission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rbac`.`permission` (
  `id` INT NOT NULL,
  `url` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rbac`.`user_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rbac`.`user_role` (
  `Users_id` INT NOT NULL,
  `Roles_id` INT NOT NULL,
  PRIMARY KEY (`Users_id`, `Roles_id`),
  INDEX `fk_Users_has_Roles_Roles1_idx` (`Roles_id` ASC),
  CONSTRAINT `fk_Users_has_Roles_Users10`
    FOREIGN KEY (`Users_id`)
    REFERENCES `rbac`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Users_has_Roles_Roles10`
    FOREIGN KEY (`Roles_id`)
    REFERENCES `rbac`.`role` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rbac`.`role_permission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rbac`.`role_permission` (
  `Roles_id` INT NOT NULL,
  `Permission_id` INT NOT NULL,
  PRIMARY KEY (`Roles_id`, `Permission_id`),
  INDEX `fk_Roles_has_Permission_Permission1_idx` (`Permission_id` ASC),
  INDEX `fk_Roles_has_Permission_Roles1_idx` (`Roles_id` ASC),
  CONSTRAINT `fk_Roles_has_Permission_Roles10`
    FOREIGN KEY (`Roles_id`)
    REFERENCES `rbac`.`role` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Roles_has_Permission_Permission10`
    FOREIGN KEY (`Permission_id`)
    REFERENCES `rbac`.`permission` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
