version: '3'
services:
  app:
      image: app
      depends_on:
        - db
      deploy:
        replicas: 5
        restart_policy:
          condition: on-failure
      ports:
        - "5000:5000"
      networks:
        - appnet
  db:
      image: db
      ports:
        - "3300:3306"
      volumes:
        - ./data:/var/lib/mysql
      environment:
        - MYSQL_DATABASE=rbac
        - MYSQL_ROOT_PASSWORD=root123456
      networks:
        - appnet
networks:
    appnet:
